name: Mazaj
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  upgrader:
  pub_semver:
  package_info:
  pull_to_refresh:
  rflutter_alert:
  firebase_messaging:
  firebase_auth:
  firebase_storage:
  cloud_firestore:
  geolocator: 5.3.2+2
  geocoder:
  flutter_rating_bar:
  firebase_core:
  location:
  dio:
  vibration:
  flutter_cache_manager:
  photo_view:
  flutter_svg:
  toast:
  dotted_line:
  http:
  cached_network_image:
  smooth_star_rating:
  google_maps_flutter:
  permission:
  flutter_google_places:
  sliding_sheet:
  shared_preferences: ^0.5.12
  flutter_polyline_points:
  bubble_tab_indicator:
  android_intent:
  image_picker: ^0.6.7+11
  intent:
  awesome_dialog:
  flutter_spinkit:
  flutter_bloc:
  auto_size_text:
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/sounds/

  fonts:
    - family: GE_SS_Two
      fonts:
        - asset: assets/fonts/GE_SS_Two_Light.otf
          weight: 300
        - asset: assets/fonts/GE_SS_Two_Medium.otf
          weight: 400
    - family: Arial
      fonts:
        - asset: assets/fonts/ARIAL.ttf
          weight: 400
        - asset: assets/fonts/ARIAL_Bold.ttf
          weight: 700
